### ISSUE TITLE
Add blazer

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#1000]
```yaml
  blazer:
    command: sh -c "rails db:migrate && puma -C /app/config/puma.rb"
    container_name: blazer
    depends_on:
      postgres:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/blazer
      - DATABASE_CUSTOMER_URL=postgres://postgres:postgres@postgres:5432/customer
    image: "ankane/blazer:${BLAZER_VERSION:-v3.1.0}"
    ports:
      - "8080:8080"
    volumes:
      - "./data/blazer/blazer.yml:/app/config/blazer.yml"
 ```
