### ISSUE TITLE
Add debezium-ui

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#1001]
```yaml
  debezium:
    container_name: debezium
    depends_on:
      debezium-connect:
        condition: service_healthy
    environment:
      - "KAFKA_CONNECT_URIS=http://debezium-connect:8083"
    healthcheck:
      interval: 10s
      retries: 3
      test: [CMD, curl, --fail, "http://localhost:8080"]
      timeout: 10s
    image: "debezium/debezium-ui:${DEBEZIUM_VERSION:-2.1.2.Final}"
    ports:
      - "8080:8080"
```
