### ISSUE TITLE
Add flightsql

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#1002]
```yaml
  flight-sql:
    command: [tail, -f, /dev/null]
    container_name: flight-sql
    depends_on:
      - duckdb
      - sqlite
    environment:
      - TLS_ENABLED=1
      - "FLIGHT_PASSWORD=${FLIGHT_SQL_PASSWORD:-flight_password}"
      - PRINT_QUERIES=1
    image: "voltrondata/flight-sql:${FLIGHT_SQL_VERSION:-v1.4.1}"
    ports:
      - "31337:31337"
 ```
