### ISSUE TITLE
Add localstack

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#1011]
```yaml
  localstack:
    image: localstack/localstack:0.14
    ports:
      - 4566:4566
      - 8080:8080
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - AWS_ACCESS_KEY_ID=deltalake
      - AWS_SECRET_ACCESS_KEY=weloverust
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/health" ]
```
