### ISSUE TITLE
Add fake-gcs

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#1012]
```yaml
  fake-gcs:
    # Custom image - see fsouza/fake-gcs-server#1164
    image: tustvold/fake-gcs-server
    command: ["-scheme", "http", "-public-host", "localhost:4443", "-backend", "memory"]
    ports:
      - 4443:4443
```
