### ISSUE TITLE
add whisper API

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#1018]
```
whisper_api:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu  # Replace with the actual Whisper image if needed
          # For GPU-enabled version -> onerahmet/openai-whisper-asr-webservice:latest-gpu
          # More info -> https://hub.docker.com/r/onerahmet/openai-whisper-asr-webservice
    container_name: whisper_api
    restart: always  # Automatically restarts the container in case of failure
    environment:
      - ASR_MODEL=turbo  # Sets the default Whisper model to 'turbo' More info -> https://github.com/openai/whisper
      - ASR_ENGINE=openai_whisper
      - NVIDIA_VISIBLE_DEVICES=all  # Allows use of all available GPUs if uncommented (for GPU-enabled versions)
    runtime: nvidia  # Required to enable GPU usage
    ports:
      - "9000:9000"  # Exposes Whisper service on port 9000
    volumes:
      - whisper_model:/root/.cache/whisper  # Maps host directory to cache Whisper model files
```

<https://hub.docker.com/r/linuxserver/faster-whisper>
