### ISSUE TITLE
Add falkorDB

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#1030]
```yml
  falkordb:
    image: falkordb/falkordb:edge
    container_name: falkordb
    profiles:
      - falkordb
    ports:
      - 6379:6379
      - 3001:3000
    networks:
      - cognee-network
```
