### ISSUE TITLE
add influxdb3-core

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#1058]
```yaml
  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    ports:
      - 9999:9999
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
```
