### ISSUE TITLE
Add Hawtio to the stack

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#107]
Add hawtio as a service:

```
  hawtio:
    image: "erikwramner/hawtio"
    container_name: hawtio
    hostname: hawtio
    ports:
      - "38085:8080"  
```
