### ISSUE TITLE
Add presidio-analyzer:

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#1086]
```yaml
  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    container_name: analyzer
    ports:
      - "5002:3000"
```
