### ISSUE TITLE
Add Superset to stack

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#15]
The visualization GUI Superset should be added to the stack. 

Use this service as a base (<https://github.com/johannestang/bigdata_stack/blob/master/docker-compose.yml>):

```
  superset:
    image: amancevice/superset:0.28.1
    restart: always
    depends_on:
      - superset-postgres
      - superset-redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - ./config/superset_config.py:/etc/superset/superset_config.py
```
