### ISSUE TITLE
Upgrade to latest Elasticsearch version

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#181]
Here the snippet from a docker-compose.yml done by Robin Moffatt. Use that to update to 7.5.0. 

```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
    environment:
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"
    volumes: 
      - ./data/container_data/elasticsearch:/usr/share/elasticsearch/data
    command: 
      - bash 
      - -c 
      - |
        /usr/local/bin/docker-entrypoint.sh & 
        echo "Waiting for Elasticsearch to start ⏳"
        while [ $$(curl -s -o /dev/null -w %{http_code} http://localhost:9200/) -eq 000 ] ; do 
          echo -e $$(date) " Elasticsearch listener HTTP state: " $$(curl -s -o /dev/null -w %{http_code} http://localhost:9200/) " (waiting for != 000)"
          sleep 5 
        done
        curl -XPUT "http://localhost:9200/_template/kafkaconnect/" -H 'Content-Type: application/json' -d'
          {
            "index_patterns": "*",
            "settings": { "number_of_shards": 1, "number_of_replicas": 0 },
            "mappings": { "dynamic_templates": [
                { "dates1": { "match": "timestamp", "mapping": { "type": "date" } } },
                { "dates3": { "match": "*_TS", "mapping": { "type": "date" } } }
            ] } }'        
        sleep infinity
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    hostname: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      xpack.security.enabled: "false"
      discovery.type: "single-node"
```
