### ISSUE TITLE
Add wireshark

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#185]
```
  wireshark:
    image: linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000 #optional
    restart: unless-stopped
```
