### ISSUE TITLE
Add StreamPipes as service

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#224]
<https://streampipes.apache.org/> and <https://github.com/apache/incubator-streampipes-installer/blob/master/compose/docker-compose.yml>

**Comment by gschmutz** [comment]
When implementing it, I realized, that with version `0.67.0` there is no way to rename the services, they have to be named "backend", ..... Until this is fixed, the change will not be activated.

```
{%if STREAMPIPES_enable | default(false) %}
  #  ================================== Apache StreamPipes ========================================== #
  streampipes-backend:
    image: apachestreampipes/backend:{{__STREAMPIPES_version}}
    container_name: streampipes-backend
    hostname: streampipes-backend
    depends_on:
      - streampipes-consul
      - streampipes-couchdb
    environment:
      CONSUL_LOCATION: streampipes-consul
    {%if use_timezone | default(false) %}
      TZ: {{use_timezone}}
    {% endif -%}   {#  use_timezone #}
    volumes:
      - ./data-transfer:/data-transfer
#      - backend:/root/.streampipes
#      - files:/spImages
    {%if use_timezone | default(false) %}
      - "./etc/timezone:/etc/timezone:ro"
      - "./etc/localtime:/etc/localtime:ro"
    {% endif -%}   {#  use_timezone #}
    restart: {{container_restart_policy}}

  streampipes-connect-master:
    image: apachestreampipes/streampipes-connect-container:{{__STREAMPIPES_version}}
    container_name: streampipes-connect-master
    hostname: streampipes-connect-master
    environment:
      EXECUTION_MODE: MASTER
      SP_CONNECT_CONTAINER_HOST: streampipes-connect-master
      SP_CONNECT_CONTAINER_WORKER: streampipes-connect-worker
    {%if use_timezone | default(false) %}
      TZ: {{use_timezone}}
    {% endif -%}   {#  use_timezone #}
    volumes:
      - ./data-transfer:/data-transfer
#      - connect:/data/
    {%if use_timezone | default(false) %}
      - "./etc/timezone:/etc/timezone:ro"
      - "./etc/localtime:/etc/localtime:ro"
    {% endif -%}   {#  use_timezone #}
    restart: {{container_restart_policy}}

  streampipes-connect-worker:
    image: apachestreampipes/connect-worker:{{__STREAMPIPES_version}}
    container_name: streampipes-connect-worker
    hostname: streampipes-connect-worker
    depends_on:
      - streampipes-consul
      - streampipes-couchdb
    environment:
      SP_CONNECT_CONTAINER_HOST: streampipes-connect-master
      SP_CONNECT_CONTAINER_WORKER: streampipes-connect-worker
    {%if use_timezone | default(false) %}
      TZ: {{use_timezone}}
    {% endif -%}   {#  use_timezone #}
    volumes:
      - ./data-transfer:/data-transfer
#      - connect:/data/
    {%if use_timezone | default(false) %}
      - "./etc/timezone:/etc/timezone:ro"
      - "./etc/localtime:/etc/localtime:ro"
    {% endif -%}   {#  use_timezone #}
    restart: {{container_restart_policy}}

  streampipes-ui:
    image: apachestreampipes/ui:{{__STREAMPIPES_version}}
    container_name: streampipes-ui
    hostname: streampipes-ui
    labels:
      com.platys.webui.title: "StreamPipes Dashboard"
      com.platys.webui.url: "http://${PUBLIC_IP}:28176"
    ports:
      - "28176:80"
    depends_on:
      - streampipes-couchdb
      - streampipes-activemq
      - streampipes-consul
      - streampipes-connect-master
      - streampipes-backend
    {%if use_timezone | default(false) %}
    environment:
      TZ: {{use_timezone}}
    {% endif -%}   {#  use_timezone #}
    volumes:
      - ./data-transfer:/data-transfer
#      - connect:/data/
    {%if use_timezone | default(false) %}
      - "./etc/timezone:/etc/timezone:ro"
      - "./etc/localtime:/etc/localtime:ro"
    {% endif -%}   {#  use_timezone #}
    restart: {{container_restart_policy}}

  streampipes-activemq:
    image: fogsyio/activemq:5.15.9
    container_name: streampipes-activemq
    hostname: streampipes-activemq
    {%if use_timezone | default(false) %}
    environment:
      TZ: {{use_timezone}}
    {% endif -%}   {#  use_timezone #}
    volumes:
      - ./data-transfer:/data-transfer
#      - connect:/data/
    {%if use_timezone | default(false) %}
      - "./etc/timezone:/etc/timezone:ro"
      - "./etc/localtime:/etc/localtime:ro"
    {% endif -%}   {#  use_timezone #}
    restart: {{container_restart_policy}}

  streampipes-consul:
    image: fogsyio/consul:1.7.1
    container_name: streampipes-consul
    hostname: streampipes-consul
    environment:
      CONSUL_LOCAL_CONFIG: '{\"disable_update_check\": true}'
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_HTTP_ADDR: 0.0.0.0
    {%if use_timezone | default(false) %}
      TZ: {{use_timezone}}
    {% endif -%}   {#  use_timezone #}
    volumes:
      - ./data-transfer:/data-transfer
#      - consul:/consul/data
    {%if use_timezone | default(false) %}
      - "./etc/timezone:/etc/timezone:ro"
      - "./etc/localtime:/etc/localtime:ro"
    {% endif -%}   {#  use_timezone #}
    restart: {{container_restart_policy}}

  streampipes-couchdb:
    image: fogsyio/couchdb:2.3.1
    container_name: streampipes-couchdb
    hostname: streampipes-couchdb
    {%if use_timezone | default(false) %}
    environment:
      TZ: {{use_timezone}}
    {% endif -%}   {#  use_timezone #}
    volumes:
      - ./data-transfer:/data-transfer
#      - couchdb:/opt/couchdb/data
    {%if use_timezone | default(false) %}
      - "./etc/timezone:/etc/timezone:ro"
      - "./etc/localtime:/etc/localtime:ro"
    {% endif -%}   {#  use_timezone #}
    restart: {{container_restart_policy}}
{% endif %}   {#  STREAMPIPES_enable #}
```
