### ISSUE TITLE
Add a global section to config.yml

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#245]
Group global settings inside a global section in the `config.yml`

```
      global: 
         use_timezone: ''
         # the name of the repository to use for private images, which are not on docker hub (currently only Oracle images)
         private_docker_repository_name: 'trivadis'
         # the UID to use when using the "user" property in a service to override the user inside the container
         uid: '1000'
```
