### ISSUE TITLE
Add Ceph

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#320]
```
  ceph:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    environment:
      - CEPH_DEMO_UID=ceph-admin
      - CEPH_DEMO_ACCESS_KEY=accesskey
      - CEPH_DEMO_SECRET_KEY=secretkey
      - CEPH_DEMO_BUCKET=demobucket
      - RGW_NAME=s3.localhost
      - RGW_CIVETWEB_PORT=8010
      - NETWORK_AUTO_DETECT=4
      - RESTAPI_LOG_LEVEL=debug
    ports:
      - 8010:8010
      - 5000:5000
    hostname: s3.localhost
    command: demo
```
