### ISSUE TITLE
Generate a documentation page with a list of UI's and API's provided by the stack

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#37]
Generate a documentation page with a table for the API's and another table for the UI's offered by the stack. 

The information can be retrieved from the labels in the generated `docker-compose.yml`file. This will be added by #36.

Medatadata for a webui will look like shown below

```
  kafka-manager:
    image: trivadis/kafka-manager:latest
    container_name: kafka-manager
    hostname: kafka-manager
    labels:
      com.mdps.service.webui.url: http://${PUBLIC_IP}:28038
```

The documentation could be as part of a Markdown file or as an web-application started as a separate container.
