### ISSUE TITLE
Support Zookeeper-less Kafka

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#376]
<https://github.com/confluentinc/cp-all-in-one/blob/6.2.0-post/cp-all-in-one-kraft/docker-compose.yml>

THis is the section

```
  broker:
      
      
            image: confluentinc/cp-kafka:6.2.0
      
      
            hostname: broker
      
      
            container_name: broker
      
      
            ports:
      
      
              - "9092:9092"
      
      
              - "9101:9101"
      
      
            environment:
      
      
              KAFKA_BROKER_ID: 1
      
      
              KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      
      
              KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      
      
              KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
      
              KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      
      
              KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      
      
              KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      
      
              KAFKA_JMX_PORT: 9101
      
      
              KAFKA_JMX_HOSTNAME: localhost
      
      
              KAFKA_PROCESS_ROLES: 'broker,controller'
      
      
              KAFKA_NODE_ID: 1
      
      
              KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      
      
              KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://localhost:9092'
      
      
              KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      
              KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      
      
              KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      
      
            volumes:
      
      
              - ./update_run.sh:/tmp/update_run.sh
      
      
            command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" &amp;&amp; exit 1 ; else /tmp/update_run.sh &amp;&amp; /etc/confluent/docker/run ; fi'"
      
      
        
```
