### ISSUE TITLE
Add Open LDAP similar to Confluent Demo

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#377]
<https://github.com/confluentinc/cp-demo/blob/6.2.0-post/docker-compose.yml>

```
  openldap:
            image: osixia/openldap:1.3.0
            hostname: openldap
            container_name: openldap
            ports:
                - 389:389
            environment:
                LDAP_ORGANISATION: "ConfluentDemo"
                LDAP_DOMAIN: "confluentdemo.io"
                LDAP_BASE_DN: "dc=confluentdemo,dc=io"
            volumes:
                - ./scripts/security/ldap_users:/container/service/slapd/assets/config/bootstrap/ldif/custom
```
