### ISSUE TITLE
Add MirrorMaker2 support

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#423]
```
  mm2:
    image: local/mirrormaker2:latest
    container_name: mm2  
    hostname: mm2   
    volumes:
      - ./data-transfer/mm2.properties:/opt/mm2/kafka-mm2.properties:ro
```
