### ISSUE TITLE
Add Maria DB service

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#51]
Add Maria DB as another RDBMS service. Use this image: <https://hub.docker.com/_/mariadb>.

In contrast to MySQL, the MariaDB image is also supported on ARM hardware.

```
  mariadb:
    image: mariadb/server:10.3
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: ha_db
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
    user: "${LOCAL_USER}:${LOCAL_USER}"
    volumes:
      # Local path where the database will be stored.
      - <local db path>:/var/lib/mysql
    ports:
      - "3306:3306"
```
