### ISSUE TITLE
Cassandra 3 nodes 2 Gateway 

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/platys-modern-data-platform#527]
How can deploy that stack?

**Comment by gschmutz** [comment]
what you mean with 2 gateway?

**Comment by gschmutz** [comment]
To have a stack with just a three node Cassandra, initialize a stack first

```bash
platys init -n demo-platform --stack trivadis/platys-modern-data-platform --stack-version 1.15.0 --structure flat
```

Now edit the config.yml and enable Cassandra with 3 nodes

```yaml
      CASSANDRA_enable: true
      # either 3 or 4
      CASSANDRA_major_version: 4
      CASSANDRA_volume_map_data: false
      CASSANDRA_nodes: 3
```

and then generate the stack

```bash
platys gen
```
