### ISSUE TITLE
Add Jenkins

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#605]
<https://github.com/jenkinsci/docker>

```yaml
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins'
    environment:
        JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - '8080:8080'
      - "50000:50000"
    volumes:
      - 'jenkins_data:/var/jenkins_home'
 ```
