### ISSUE TITLE
Add downloading maven dependencies to flink

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#664]
```
  downloader:
    container_name: downloader
    image: everpeace/curl-jq
    entrypoint: ["/usr/src/app/maven-download.sh", "central", "org.apache.flink:flink-sql-connector-kafka:1.17.0,org.apache.flink:flink-sql-connector-kafka:1.16.0", "/tmp/jars"]
    volumes:
      - ./scripts/docker/maven-download.sh:/usr/src/app/maven-download.sh
      - ./data-transfer:/tmp/jars
 ```
