### ISSUE TITLE
Add support for Streamlit

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#702]
<https://docs.streamlit.io>
<https://docs.streamlit.io/knowledge-base/tutorials/deploy/docker>

```
    app:
        build: ./
        command: streamlit run app/main.py --server.port 8501
        volumes:
            - ./:/usr/src/app
        ports:
            - 8501:8501
        image: yourstreamlitapp:latest
```
