### ISSUE TITLE
Add support for Mage

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#703]
<https://github.com/mage-ai/mage-ai#%EF%B8%8F-quick-start>

```yaml
  mage-ai:
    command: mage start your_first_project
    container_name: mage-ai
    environment:
      - USER_CODE_PATH=/home/src/your_first_project
    image: "mageai/mageai:${MAGE_AI_VERSION:-0.9.75}"
    ports:
      - "6789:6789"
    restart: on-failure
```
