### ISSUE TITLE
Remove environment variables $PUBLIC_IP from metadata in docker-compose.yml

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#704]
Currently the environment variable $PUBLIC_IP is used in the labels section of the `docker-compose.yml` file: 

```yml
    labels:
      com.platys.name: wetty
      com.platys.webui.title: WeTTY UI
      com.platys.webui.url: http://${PUBLIC_IP}:3001
```

This is problematic, if the value of the variable is changed and the stack is running, as it will force the recreation of the container, due to the desired state != actual state.
