### ISSUE TITLE
Add FluentD as a logging driver

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#709]
```yml
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: docker
```
