### ISSUE TITLE
Add FluentD

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#710]
```yml
  fluentd:
    container_name: test_fluentd
    restart: always
    image: fluent/fluentd:v1.1.1-onbuild
    volumes:
      - $PWD:/fluentd/etc
    ports:
      - "24224:24224"
    networks:
      - test_net
```

<https://docs.fluentd.org/v/0.12/container-deployment/docker-compose>
