### ISSUE TITLE
Add asyncapi-studio

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#734]
```yaml
  asyncapi-studio:
    image: asyncapi/studio:1.0.0
    container_name: asyncapi-studio
    hostname: asyncapi-studio
    labels:
      ch.postfinance.name: asyncapi-studio
    ports:
      - "8000:80"
    expose:
      - "80"
    volumes:
      - ../event-publisher/src/main/avro:/usr/share/nginx/html/avro
      - ./data-transfer:/data-transfer
    restart: unless-stopped
```
