### ISSUE TITLE
Add Basic Authentication to AKHQ

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#742]
<https://akhq.io/docs/configuration/authentifications/basic-auth.html>

```yaml
      AKHQ_CONFIGURATION: |
        micronaut:
          security:
            enabled: true
            default-group: no-roles
        akhq:
          security:
            enabled: true
            default-group: no-roles
            basic-auth:
              - username: admin
                password: "$2a$10$8guvtORdrq.1R1lpDmeVtOke7.W1OKnBdrkKalr59VCW7cwRe.6n2"
                passwordHash: BCRYPT
                groups:
                - admin
```
