### ISSUE TITLE
Add MailHog

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#747]
```yaml
  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"
```
