### ISSUE TITLE
Add healthcheck test section to all services similar to etcd

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#760]
add after `restart:` section

```
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/4566; exit $$?;'
        - bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5690; exit $$?;'
      interval: 1s
      timeout: 5s
```
