### ISSUE TITLE
NiFi Properties

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#764]
The following properties are not yet supported by environment variable in NiFi. This could be added, once support for Env Vars is available:

```yml
      # overwrite nifi.properties configurations
      NIFI_FLOW_CONFIGURATION_ARCHIVE_ENABLED: '{{NIFI_flow_configuration_archive_enable | default(true) }}'
      NIFI_FLOW_CONFIGURATION_ARCHIVE_MAX_TIME: '{{NIFI_flow_configuration_archive_max_time | default(omit) }}'
      NIFI_FLOW_CONFIGURATION_ARCHIVE_MAX_STORAGE: '{{NIFI_flow_configuration_archive_max_storage | default(omit) }}'
      NIFI_FLOW_CONFIGURATION_ARCHIVE_MAX_COUNT: '{{NIFI_flow_configuration_archive_max_count | default(omit) }}'
      NIFI_QUEUE_BACKPRESSURE_COUNT: '{{NIFI_queue_backpressure_count | default(omit) }}'
      NIFI_QUEUE_BACKPRESSURE_SIZE: '{{NIFI_queue_backpressure_size | default(omit) }}'
      NIFI_CONTENT_REPOSITORY_ARCHIVE_ENABLED: '{{NIFI_content_repository_archive_enable | default(true) }}'
      NIFI_CONTENT_REPOSITORY_ARCHIVE_MAX_RETENTION_PERIOD: '{{NIFI_content_repository_archive_max_retention_period | default(omit) }}'
      NIFI_PROVENANCE_REPOSITORY_MAX_STORAGE_TIME: '{{NIFI_provenance_repository_max_storage_time | default(omit) }}'
      NIFI_PROVENANCE_REPOSITORY_MAX_STORAGE_SIZE: '{{NIFI_provenance_repository_max_storage_size | default(omit) }}'
      NIFI_UI_AUTOREFRESH_INTERVAL: '{{NIFI_ui_autorefresh_interval| default(omit) }}'
      NIFI_ANALYTICS_PREDICT_ENABLED: '{{NIFI_analytics_predict_enable | default(true) }}'
```

and the `config.yml`

```yml
      NIFI_flow_configuration_archive_enable: true
      NIFI_flow_configuration_archive_max_time: 30 days
      NIFI_flow_configuration_archive_max_storage: 500 MB
      NIFI_flow_configuration_archive_max_count: 
      NIFI_queue_backpressure_count: 10000
      NIFI_queue_backpressure_size: 1 GB  
      NIFI_content_repository_archive_enable: true
      NIFI_content_repository_archive_max_retention_period: 7 days
      NIFI_provenance_repository_max_storage_time: 30 days
      NIFI_provenance_repository_max_storage_size: 10 GB
      NIFI_ui_autorefresh_interval: 30 sec
      NIFI_analytics_predict_enable: false      
```
