### ISSUE TITLE
Add proton (timeplus)

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#767]
<https://github.com/timeplus-io/proton/blob/develop/docker/compose/docker-compose.yml>

```yaml
  proton:
    image: ghcr.io/timeplus-io/proton:latest
    pull_policy: always
    ports:
      - 8463:8463
      - 3218:3218
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=show+create+comment || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s  
```
