### ISSUE TITLE
Add support for FileBeat

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#790]
```
    filebeat:
        container_name: filebeat
        depends_on:
            - master
        build:
            context: ./filebeat 
            dockerfile: Dockerfile
        environment:
            ELASTICSEARCH_HOST: localhost:10080
        ports:
            - 9200
        volumes:
            - ./filebeat/logs:/usr/share/filebeat/log
            # - ./filebeat/logs:/usr/share/filebeat/logs 
        networks:
            - elk
        command: ["--strict.perms=false"]
```
