### ISSUE TITLE
Add apollo router

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#795]
<https://www.apollographql.com/docs/router/containerization/docker/>

**Comment by gschmutz** [comment]
```yml
services:
  router:
    image: ghcr.io/apollographql/router:v2.10.0
    ports:
      - "4000:4000"
    volumes:
      - ./router.yaml:/dist/config/router.yaml
      - ./supergraph.graphql:/dist/config/supergraph.graphql
    command: >
      --config /dist/config/router.yaml
      --supergraph /dist/config/supergraph.graphql
    environment:
      - APOLLO_GRAPH_REF=          # optional, only needed for GraphOS managed federation
      - APOLLO_KEY=                # optional, same
```
