### ISSUE TITLE
Add OPA

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#799]
```
  opa:
    image: openpolicyagent/opa:0.60.0
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--set=decision_logs.console=true"
      - "--set=services.authz.url=http://nginx"
      - "--set=bundles.authz.service=authz"
      - "--set=bundles.authz.resource=bundle.tar.gz"
    depends_on:
      - nginx
 ```
