### ISSUE TITLE
add azurite

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#805]
<https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=docker-hub%2Cblob-storage#run-azurite>

```yaml
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
```
