### ISSUE TITLE
Add Apache Ranger as a service?

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#87]
I have played with the idea of adding Apache Ranger to the stack a while ago. Here is the snippet I have used:

```     
  ranger-admin:
    image: wbaa/rokku-dev-apache-ranger:0.0.17
    container_name: ranger-admin
    stdin_open: true
    tty: true
    depends_on:
      - "postgres-server"
      - "ceph"
    ports:
      - "6080:6080"

  ceph:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: ceph
    environment:
      - CEPH_DEMO_UID=ceph-admin
      - CEPH_DEMO_ACCESS_KEY=accesskey
      - CEPH_DEMO_SECRET_KEY=secretkey
      - CEPH_DEMO_BUCKET=demobucket
      - RGW_NAME=localhost
      - RGW_CIVETWEB_PORT=8010
      - NETWORK_AUTO_DETECT=4
      - RESTAPI_LOG_LEVEL=debug
    ports:
      - 8010:8010
      - 35000:5000
    command: demo

  postgres-server:
    image: wbaa/rokku-dev-apache-ranger-postgres:0.0.17
    container_name: postgres-server
```

Re-check, if adding Ranger makes sense. 

Yes, it definitely does make sense, as Starburst Data Presto now works with Ranger for fine-grained access.
