### ISSUE TITLE
Add fuseki

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#876]
```
fuseki:
    container_name: d2s-fuseki
    image: stain/jena-fuseki:3.14.0
    environment: 
      - FUSEKI_DATASET_1=demo
      - ADMIN_PASSWORD=password 
      - JVM_ARGS=-Xmx2g # Default: 1200MiB
    ports:
      - 3030:3030
    volumes:
      - ../workspace/fuseki:/fuseki
      - ../workspace/import:/staging
    networks:
      - network
    restart: unless-stopped>
```
