### ISSUE TITLE
Add ORDS (Oracle REST Data Service) to stack

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#88]
Support available here: <https://github.com/oracle/docker-images/tree/master/OracleRestDataServices>

First you have to build the `OracleJava` docker image. Download the latest server-jre-8uNNN-linux-x64.tar.gz and build it

```
./build.sh
```

Then in the `OracleRestDatabaseService` folder build the Oracle REST Data Service docker image 

```
./buildDockerImage.sh -i
```

Run a standalone instance using the following command

```
docker run --name <container name> \
--network=<name of your created network> \
-p 8888:8888 \
-e ORACLE_HOST=oracle-db \
-e ORACLE_PORT=1521 \
-e ORACLE_SERVICE=XEPDB1 \
-e ORACLE_PWD=manager \
-e ORDS_PWD=manager \
-v [<host mount point>:]/opt/oracle/ords/config/ords \
oracle/restdataservices:18.4.0
```

Or add it as a service to a docker-compose configuration

```
  oracle-rest-1:
    image: oracle/restdataservices:18.4.0
    container_name: oracle-rest-1
    ports:
      - "8888:8888"
    environment:
      ORACLE_HOST: oracle-db
      ORACLE_PORT: 1521
      ORACLE_SERVICE: XEPDB1
      ORACLE_PWD: manager
      ORDS_PWD: manager
    restart: always
```
