### ISSUE TITLE
add searxng

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#898]
```
services:
  searxng:
    container_name: ${HARBOR_CONTAINER_PREFIX}.searxng
    env_file: ./.env
    image: searxng/searxng
    environment:
      INSTANCE_NAME: searxng
      BASE_URL: http://0.0.0.0:8080
    volumes:
      - ./searxng:/etc/searxng
    ports:
      - ${HARBOR_SEARXNG_HOST_PORT}:8080
    networks:
      - harbor-network
```
